### PR TITLE
Support Creating Links in Terminals

### PR DESCRIPTION
**Pull request by lenary**
This is quite an invasive set of changes, with the aim of also
highlighting keywords in terminal sessions. This adds `terminal` to the
config to support terminals, and raises the minimum vscode version to
1.49.0.

I also took the time to refactor how matching works. We now combine all
the regexps into one, and search for it everywhere, and then when we
have a match, we work out which specific regexp created the match. This
means we only register one link provider per language, and so there is
better control of prioritization between rules. As this logic is fairly
complex, I put it in a new class called MultiRuleMatcher, which both the
LinkProviders subclass. The tests now also use a subclass of
MultiRuleMatcher rather than the DocumentLinkProvider, so they don't
require a partially mocked vscode to run.

---

One specific query I have is how to extract the test suite so it doesn't need to download and launch vscode, as the tests no longer rely on launching an editor instance and mocking out a fake document.

### CODE REVIEW

**Comment by dlevs** [comment]
Hey, thanks for raising this! At a glance, this all looks sensible and the ability to have terminal links is cool. :)

I want to try it out and review it properly, but doubt I'll find time to do this month. If you're happy to wait, I'll get around to checking out these changes when I can, and I do intend to merge them in. Or, feel free to launch a "competing" plugin based on fork if you prefer.

**Comment by lenary** [comment]
I made myself a prerelease package including this PR which I can use in the meantime, and am happy to wait. :)

**Comment by dlevs** [comment]
Hey @lenary,

Thanks again for your input. It has been a while, but you might be interested to know I've taken your changes on board for a new extension I've been working on: [Regex Robin](https://marketplace.visualstudio.com/items?itemName=DanLevett.regex-robin). It does everything "Pattern Links" does, and more (mainly ability to style matches).

It [adds terminal links](https://github.com/dlevs/vscode-regex-robin/blob/main/src/links.ts) (thanks for the suggestion), and uses vitest, so it doesn't need the entirety of VSCode / electron to run tests.

The "combine everything into a single" regex approach is interesting, but this new extension makes use of the capture groups for styling a subset of the match, so it looks like it needs separate regexes still.

Any thoughts, feedback or suggestions, I'm all ears!

**Comment by lenary** [comment]
The "compile to one regex" means you don't get overlapping spans, and means priority isn't weirdly implicit in the rule config. If you look at my implementation, I still have to look at the matched text to work out which regex matched to get the right link - which is what you'd need for the formatting too. It also much more clearly treats the "g" flag IIRC.

**Pull request closed without merging**
